name: Auto Format with Clang

on: 
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name  }}
          token: ${{ secrets.PAT_FOR_ACTIONS }}

      - name: Install clang-format 14
        run: |
          sudo apt-get update
          if apt-cache show clang-format-14 &>/dev/null; then
            sudo apt-get install -y clang-format-14
          else
            sudo apt-get install -y clang-format
          fi

      - name: Run clang-format
        run: ./fix_formatting.sh


      # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-to-a-pr-using-the-built-in-token
      - name: Check and commit changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            git diff
            git commit -am "chore: auto-format with clang-format"
            git push
          else
            echo "No formatting changes"
          fi

    
