name: Reusable Build ce.dat

on:
  workflow_call:
    inputs:
      preset:
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-ce-dat:
    name: Build ce.dat
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install libsdl2-dev zlib1g-dev

      - name: Configure
        run: |
          cmake --preset ${{ inputs.preset }}

      - name: Build ce-dat-tool
        run: |
          cmake --build --preset ${{ inputs.preset }} --target ce-dat-tool

      - name: Create ce.dat
        run: |
          mkdir -p out/dist
          out/build/${{ inputs.preset }}/ce-dat-tool create files/ce.dat out/dist/ce.dat

      - name: Upload ce.dat artifact
        uses: actions/upload-artifact@v4
        with:
          name: ce-dat
          path: out/dist/ce.dat
          retention-days: 7
